# Generated by Django 5.2.8 on 2025-11-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epi',
            name='categoria',
            field=models.CharField(choices=[('capacete', 'Capacete'), ('luva', 'Luva'), ('caneleira', 'Caneleira'), ('bota', 'Bota'), ('mascara', 'Máscara'), ('outro', 'Outro')], default='outro', max_length=50),
        ),
    ]
