# Generated by Django 5.2.8 on 2025-11-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='idade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
