# Generated by Django 5.2.8 on 2025-11-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0002_colaborador_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
