# Generated by Django 5.2.8 on 2025-11-22 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0003_colaborador_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='foto_colaborador',
        ),
    ]
